language: java
jdk:
  - oraclejdk8
  - openjdk8
install: true
before_script:
  - chmod +x gradlew
script:
  - ./gradlew clean build
  - ./gradlew check
  - ./gradlew codeCoverageReport
after_success:
  - bash <(curl -s https://codecov.io/bash)
sudo: false
addons:
  apt:
    packages:
      - oracle-java8-installer
